export type Formation = {
  id: string;
  name: string;
  slug: string;
  category: string;
  price: number;
  pricePromo?: number;
  shortDesc: string;
  longDesc: string;
  objectives: string[];
  prerequisites: string[];
  skills: string[];
  careers: string[];
  duration: string;
  modality: 'Présentiel' | 'En ligne' | 'Hybride';
  level: string;
  city: string;
  status: 'Actif' | 'Brouillon';
  featured: boolean;
  image: string;
};

export const GALF_FORMATIONS: Formation[] = [
  {
    id: "f-01",
    name: "Carte de l'opérateur",
    slug: "carte-operateur",
    category: "Certifications",
    price: 15000,
    shortDesc: "Validation officielle d'aptitude à la conduite d'engins.",
    longDesc: "Obtenez votre carte professionnelle indispensable pour exercer en tant qu'opérateur d'engins lourds en toute légalité et sécurité.",
    objectives: ["Valider ses acquis", "Obtenir la certification officielle"],
    prerequisites: ["Savoir lire et écrire", "Expérience pratique préalable"],
    skills: ["Conduite sécurisée", "Règles HSE de base"],
    careers: ["Opérateur certifié", "Conducteur d'engins BTP"],
    duration: "2 jours",
    modality: 'Présentiel',
    level: "Tous niveaux",
    city: "Abidjan",
    status: 'Actif',
    featured: false,
    image: "/images/formations/carte-operateur.jpg"
  },
  {
    id: "f-02",
    name: "Chariot élévateur",
    slug: "chariot-elevateur",
    category: "Logistique",
    price: 130000,
    shortDesc: "Maîtrise de la conduite de chariots élévateurs en milieu industriel.",
    longDesc: "Formation complète pour devenir cariste professionnel, incluant les manœuvres de précision et les règles de sécurité strictes en entrepôt.",
    objectives: ["Manoeuvrer un chariot élévateur avec précision", "Appliquer les consignes de sécurité en entrepôt"],
    prerequisites: ["Etre âgé de 18 ans minimum", "Aptitude médicale"],
    skills: ["Manutention", "Gerbage", "Sécurité logistique"],
    careers: ["Cariste", "Magasinier cariste"],
    duration: "2 semaines",
    modality: 'Présentiel',
    level: "Débutant",
    city: "Abidjan",
    status: 'Actif',
    featured: true,
    image: "/images/formations/chariot-elevateur.jpg"
  },
  {
    id: "f-03",
    name: "HSE (Hygiène, Sécurité, Environnement)",
    slug: "hse",
    category: "Sécurité",
    price: 130000,
    shortDesc: "Fondamentaux et gestion de la sécurité sur chantier et en industrie.",
    longDesc: "Devenez un maillon essentiel de la prévention des risques professionnels. Formation intensive aux normes internationales HSE.",
    objectives: ["Identifier les risques professionnels", "Mettre en place des plans de prévention"],
    prerequisites: ["Niveau BAC recommandé"],
    skills: ["Prévention des risques", "Sauvetage", "Audits de sécurité"],
    careers: ["Animateur HSE", "Superviseur Sécurité"],
    duration: "3 semaines",
    modality: 'Hybride',
    level: "Intermédiaire",
    city: "Abidjan",
    status: 'Actif',
    featured: false,
    image: "/images/formations/hse.jpg"
  },
  {
    id: "f-04",
    name: "Anglais minier",
    slug: "anglais-minier",
    category: "Formations complémentaires",
    price: 150000,
    shortDesc: "Anglais technique spécifique à l'industrie minière et pétrolière.",
    longDesc: "Boostez votre employabilité à l'international ou auprès des multinationales opérant en Afrique avec ce module d'anglais ultra-spécialisé.",
    objectives: ["Communiquer sur un site minier", "Comprendre la documentation technique en anglais"],
    prerequisites: ["Niveau d'anglais de base"],
    skills: ["Vocabulaire minier", "Communication radio", "Lecture technique"],
    careers: ["Opérateur international", "Superviseur bilingue"],
    duration: "1 mois",
    modality: 'En ligne',
    level: "Intermédiaire",
    city: "En ligne",
    status: 'Actif',
    featured: false,
    image: "/images/formations/anglais-minier.jpg"
  },
  {
    id: "f-05",
    name: "Pelle hydraulique",
    slug: "pelle-hydraulique",
    category: "Engins de chantier",
    price: 230000,
    shortDesc: "Conduite et manœuvres de pelles hydrauliques sur chenilles et pneus.",
    longDesc: "Une formation pratique intensive pour maîtriser l'engin roi des chantiers de terrassement et d'extraction.",
    objectives: ["Effectuer des travaux de terrassement", "Maîtriser les mouvements combinés de la pelle"],
    prerequisites: ["Etre âgé de 18 ans minimum", "Aptitude médicale confirmée"],
    skills: ["Terrassement", "Nivellement", "Entretien de 1er niveau"],
    careers: ["Conducteur de pelle", "Opérateur terrassement"],
    duration: "1 mois",
    modality: 'Présentiel',
    level: "Débutant",
    city: "San Pedro",
    status: 'Actif',
    featured: true,
    image: "/images/formations/pelle-hydraulique.jpg"
  },
  {
    id: "f-06",
    name: "Chargeuse",
    slug: "chargeuse",
    category: "Engins de chantier",
    price: 230000,
    shortDesc: "Maîtrise de la conduite d'une chargeuse sur pneus ou chenilles.",
    longDesc: "Apprenez à charger, transporter et décharger des matériaux avec une efficacité et une sécurité maximales.",
    objectives: ["Remplir le godet de manière optimale", "Sécuriser la zone de chargement"],
    prerequisites: ["Permis de conduire recommandé"],
    skills: ["Manutention de vrac", "Chargement de camions"],
    careers: ["Conducteur de chargeuse"],
    duration: "1 mois",
    modality: 'Présentiel',
    level: "Débutant",
    city: "Abidjan",
    status: 'Actif',
    featured: false,
    image: "/images/formations/chargeuse.jpg"
  },
  {
    id: "f-07",
    name: "Sino Truck",
    slug: "sino-truck",
    category: "Transport lourd",
    price: 230000,
    shortDesc: "Conduite de camions lourds Sino Truck pour le BTP et la mine.",
    longDesc: "Devenez expert dans la conduite de ces camions incontournables sur les grands projets d'infrastructure africains.",
    objectives: ["Conduire un camion lourd en toute sécurité", "Effectuer le basculement de la benne"],
    prerequisites: ["Permis poids lourd (C ou E)"],
    skills: ["Conduite de benne", "Sécurité routière avancée"],
    careers: ["Chauffeur poids lourds BTP"],
    duration: "3 semaines",
    modality: 'Présentiel',
    level: "Avancé",
    city: "Yamoussoukro",
    status: 'Actif',
    featured: false,
    image: "/images/formations/sino-truck.jpg"
  },
  {
    id: "f-08",
    name: "Grue mobile",
    slug: "grue-mobile",
    category: "Levage",
    price: 250000,
    shortDesc: "Opération de grues mobiles sur camions pour chantiers complexes.",
    longDesc: "Une formation de très haute précision pour devenir grutier, un métier extrêmement recherché et bien rémunéré.",
    objectives: ["Mettre en station la grue", "Réaliser des opérations de levage délicates"],
    prerequisites: ["Bases en mathématiques/physique", "Bonne vue"],
    skills: ["Levage de précision", "Calcul de charge", "Élingage"],
    careers: ["Grutier mobile", "Chef de manœuvre"],
    duration: "1.5 mois",
    modality: 'Présentiel',
    level: "Intermédiaire",
    city: "Abidjan",
    status: 'Actif',
    featured: true,
    image: "/images/formations/grue-mobile.jpg"
  },
  {
    id: "f-09",
    name: "Grue auxiliaire",
    slug: "grue-auxiliaire",
    category: "Levage",
    price: 250000,
    shortDesc: "Conduite de camions équipés d'une grue auxiliaire de chargement.",
    longDesc: "Idéal pour le transport de matériaux. Vous maîtriserez à la fois la conduite du poids lourd et la manutention mécanisée.",
    objectives: ["Utiliser la grue embarquée en sécurité"],
    prerequisites: ["Permis Poids Lourd"],
    skills: ["Élingage", "Conduite bras articulé"],
    careers: ["Chauffeur-Livreur Grutier"],
    duration: "3 semaines",
    modality: 'Présentiel',
    level: "Intermédiaire",
    city: "Abidjan",
    status: 'Actif',
    featured: false,
    image: "/images/formations/grue-auxiliaire.jpg"
  },
  {
    id: "f-10",
    name: "Challenger",
    slug: "challenger",
    category: "Transport lourd",
    price: 300000,
    shortDesc: "Conduite de tracteurs agricoles et forestiers lourds de type Challenger.",
    longDesc: "Formation ultra-spécifique pour les grandes exploitations agro-industrielles et forestières exigeant puissance et précision.",
    objectives: ["Opérer un tracteur de très forte puissance", "Utiliser les outils attelés"],
    prerequisites: ["Expérience en conduite agricole"],
    skills: ["Agriculture lourde", "Traction"],
    careers: ["Conducteur de machines agricoles lourdes"],
    duration: "1 mois",
    modality: 'Présentiel',
    level: "Avancé",
    city: "San Pedro",
    status: 'Actif',
    featured: false,
    image: "/images/formations/challenger.jpg"
  },
  {
    id: "f-11",
    name: "Bulldozer",
    slug: "bulldozer",
    category: "Engins de chantier",
    price: 310000,
    shortDesc: "Maniement du bouteur pour le terrassement de grande masse.",
    longDesc: "Incarnez la puissance pure du chantier. Apprenez à pousser, décaper et niveler avec un haut rendement.",
    objectives: ["Maîtriser le décapage de terre végétale", "Réaliser des opérations de refoulement"],
    prerequisites: ["Aptitude médicale"],
    skills: ["Refoulement", "Travail en pente", "Entretien machine"],
    careers: ["Conducteur de Bouteur (Bulldozer)"],
    duration: "1 mois",
    modality: 'Présentiel',
    level: "Débutant",
    city: "Bouaké",
    status: 'Actif',
    featured: true,
    image: "/images/formations/bulldozer.jpg"
  },
  {
    id: "f-12",
    name: "Tractopelle",
    slug: "tractopelle",
    category: "Engins de chantier",
    price: 350000,
    shortDesc: "L'engin polyvalent : maîtrise de la pelle rétro et du godet chargeur.",
    longDesc: "L'engin le plus recherché sur les chantiers urbains. Une formation double compétence exigeante et très valorisée.",
    objectives: ["Creuser des tranchées avec précision", "Charger et niveler frontalement"],
    prerequisites: ["Bonne coordination psychomotrice"],
    skills: ["Vérifications (VGP)", "Fouilles", "Chargement"],
    careers: ["Conducteur de tractopelle"],
    duration: "1.5 mois",
    modality: 'Présentiel',
    level: "Débutant",
    city: "Abidjan",
    status: 'Actif',
    featured: false,
    image: "/images/formations/tractopelle.jpg"
  },
  {
    id: "f-13",
    name: "Tombereau articulé",
    slug: "tombereau-articule",
    category: "Engins de chantier",
    price: 350000,
    shortDesc: "Conduite d'engins de transport de matériaux hors route.",
    longDesc: "Indispensable dans les grandes carrières et terrassements. Maîtrisez la conduite sur terrains difficiles et glissants.",
    objectives: ["Conduire sur pistes de chantier aménagées", "Effectuer le vidage en sécurité"],
    prerequisites: ["Permis C recommandé"],
    skills: ["Conduite en terrain meuble", "Respect des cycles de production"],
    careers: ["Conducteur de tombereau articulé (Dumper)"],
    duration: "1 mois",
    modality: 'Présentiel',
    level: "Intermédiaire",
    city: "Abidjan",
    status: 'Actif',
    featured: false,
    image: "/images/formations/tombereau-articule.jpg"
  },
  {
    id: "f-14",
    name: "Tombereau rigide",
    slug: "tombereau-rigide",
    category: "Mine",
    price: 350000,
    shortDesc: "Conduite de tombereaux miniers géants (Trucks).",
    longDesc: "Accédez aux carrières minières les plus prestigieuses avec cette formation sur les monstres sacrés de l'extraction.",
    objectives: ["Maîtriser les gabarits exceptionnels", "Appliquer les procédures minières strictes"],
    prerequisites: ["Expérience réussie en tombereau articulé ou poids lourd"],
    skills: ["Conduite minière", "Procédures d'urgence en mine"],
    careers: ["Opérateur minier", "Conducteur de truck"],
    duration: "1.5 mois",
    modality: 'Présentiel',
    level: "Avancé",
    city: "Korhogo",
    status: 'Actif',
    featured: true,
    image: "/images/formations/tombereau-rigide.jpg"
  },
  {
    id: "f-15",
    name: "Compacteur",
    slug: "compacteur",
    category: "Engins de chantier",
    price: 350000,
    shortDesc: "Maîtrise du compactage de sols et d'enrobés.",
    longDesc: "Découvrez les techniques pointues pour obtenir la densité requise sur les chantiers routiers et de plateforme.",
    objectives: ["Régler les paramètres de vibration", "Respecter les plans de balayage"],
    prerequisites: ["Aptitude médicale"],
    skills: ["Cylindrage", "Finition de surface"],
    careers: ["Régleur compacteur", "Opérateur d'enrobés"],
    duration: "1 mois",
    modality: 'Présentiel',
    level: "Débutant",
    city: "Abidjan",
    status: 'Actif',
    featured: false,
    image: "/images/formations/compacteur.jpg"
  },
  {
    id: "f-16",
    name: "Forage hydraulique",
    slug: "forage-hydraulique",
    category: "Mine",
    price: 450000,
    shortDesc: "Techniques de forage pour puits d'eau et études géotechniques.",
    longDesc: "Devenez maître foreur et participez activement à l'accès à l'eau potable et à la préparation géologique des chantiers.",
    objectives: ["Mettre en place une foreuse", "Réaliser un tubage"],
    prerequisites: ["Connaissances techniques ou mécaniques"],
    skills: ["Forage au marteau fond de trou", "Boue de forage"],
    careers: ["Chef de sonde", "Aide-foreur"],
    duration: "2 mois",
    modality: 'Présentiel',
    level: "Intermédiaire",
    city: "Yamoussoukro",
    status: 'Actif',
    featured: false,
    image: "/images/formations/forage-hydraulique.jpg"
  },
  {
    id: "f-17",
    name: "Forage minier",
    slug: "forage-minier",
    category: "Mine",
    price: 500000,
    shortDesc: "Forage d'exploration et de production (minage) en carrière.",
    longDesc: "Une formation de pointe exigée par l'industrie minière internationale. Précision, puissance et très haute technicité.",
    objectives: ["Réaliser des plans de foration", "Maitriser les outils diamantés ou tricones"],
    prerequisites: ["Niveau BAC ou expérience en fonderie/mine"],
    skills: ["Carottage", "Sécurité explosifs"],
    careers: ["Foreur minier (Driller)"],
    duration: "2 mois",
    modality: 'Présentiel',
    level: "Avancé",
    city: "Korhogo",
    status: 'Actif',
    featured: true,
    image: "/images/formations/forage-minier.jpg"
  },
  {
    id: "f-18",
    name: "Grue à tour",
    slug: "grue-tour",
    category: "Levage",
    price: 550000,
    pricePromo: 490000,
    shortDesc: "Opération de grues à tour en cabine et radiocommandées.",
    longDesc: "Prenez de la hauteur avec le métier de grutier à tour, la pièce maîtresse absolue de la construction de bâtiments en hauteur.",
    objectives: ["Maitriser le balancé de charge", "Communiquer efficacement par gestes et radio"],
    prerequisites: ["Absence de vertige confirmée médicalement"],
    skills: ["Levage en aveugle", "Sécurité vent tempête"],
    careers: ["Grutier à tour (GMA / GME)"],
    duration: "2 mois",
    modality: 'Présentiel',
    level: "Avancé",
    city: "Abidjan",
    status: 'Actif',
    featured: true,
    image: "/images/formations/grue-tour.jpg"
  },
  {
    id: "f-19",
    name: "Porte-char",
    slug: "porte-char",
    category: "Transport lourd",
    price: 850000,
    shortDesc: "Conduite de convoi exceptionnel et manipulation des porte-chars.",
    longDesc: "La formation la plus avancée du marché routier. Acheminer en sécurité les engins de plusieurs dizaines de tonnes sur tout le territoire.",
    objectives: ["Charger et arrimer un engin de chantier lourd", "Conduire un ensemble articulé hors gabarit"],
    prerequisites: ["Permis EC avec expérience solide"],
    skills: ["Arrimage lourd", "Règles convoi exceptionnel"],
    careers: ["Chauffeur porte-char", "Conducteur convoi exceptionnel"],
    duration: "2 mois",
    modality: 'Présentiel',
    level: "Expert",
    city: "Abidjan",
    status: 'Actif',
    featured: true,
    image: "/images/formations/porte-char.jpg"
  }
];

/* 🏗️ Spécifications techniques détaillées pour l'explorateur 3D */
export const EQUIPMENT_SPECS: Record<string, any> = {
  'pelle-hydraulique': {
    power: "280 HP",
    weight: "32 Tonnes",
    depth: "7.5m",
    bucket: "1.8 m³",
    features: ["Contrôle intelligent de puissance", "Moteur Stage V", "Caméra 360°"]
  },
  'grue-tour': {
    height: "65m",
    load: "12 Tonnes",
    reach: "60m",
    speed: "Hoisting: 120m/min",
    features: ["Système anti-collision", "Cabine climatisée", "Montage rapide"]
  },
  'bulldozer': {
    power: "310 HP",
    weight: "25 Tonnes",
    blade: "6.2 m³",
    transmission: "Hydrostatique",
    features: ["Assistance de nivellement", "Chenilles renforcées", "Mode Éco"]
  },
  'chariot-elevateur': {
    capacity: "5 Tonnes",
    liftHeight: "4.5m",
    engine: "Diesel / Électrique",
    tilt: "6°/12°",
    features: ["Mât triplex", "Déplacement latéral", "Cabine ergonomique"]
  },
  'chargeuse': {
    power: "220 HP",
    weight: "18 Tonnes",
    capacity: "3.5 m³",
    transmission: "Powershift",
    features: ["Pneus L3 haute résistance", "Godet à déversement latéral", "Siège suspendu"]
  },
  'grue-mobile': {
    capacity: "100 Tonnes",
    sections: "6 Sections",
    jib: "22m",
    carrier: "8x6x8",
    features: ["Système LICCON2", "Contrepoids amovible", "Cabine inclinable"]
  },
  'tombereau-rigide': {
    payload: "65 Tonnes",
    power: "750 HP",
    volume: "42 m³",
    brakes: "Oil-cooled",
    features: ["Système de pesage embarqué", "Retardeur hydraulique", "Châssis rigide haute résistance"]
  },
  'tractopelle': {
    power: "110 HP",
    digDepth: "5.8m",
    loaderCap: "1.1 m³",
    steering: "4 roues directrices",
    features: ["Bras extensible", "Godet 4-en-1", "Transmission Torque Lock"]
  }
};
